Feature/opus
OpenMined/PyDentity pull request #25
Opened 2020-09-26 15:03 UTC by H4LL

## Description
- Adds Opus notebook demo to projects
- Redraws graphics

## Affected Dependencies
none

## How has this been tested?
Notebooks have been tested by me.

2020-09-26 19:30 UTC, TTitcombe requested changes

2020-09-26 19:30 UTC, TTitcombe commented on projects/pryvote/README.md
>  # PryVote
This branch has some outdated pryvote stuff in it. Can you remove this, and I'll open a separate PR for pryvote?

2020-09-27 11:44 UTC, H4LL commented on projects/pryvote/README.md
>  # PryVote
yup

2020-09-27 17:40 UTC, TTitcombe approved these changes

2020-09-27 17:40 UTC, merged